
package borgun.heimir.pub.ws.authorization;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Authorization", targetNamespace = "http://Borgun/Heimir/pub/ws/Authorization", wsdlLocation = "https://gatewaytest.borgun.is/ws/Heimir.pub.ws:Authorization?wsdl")
public class Authorization
    extends Service
{

    private final static URL AUTHORIZATION_WSDL_LOCATION;
    private final static WebServiceException AUTHORIZATION_EXCEPTION;
    private final static QName AUTHORIZATION_QNAME = new QName("http://Borgun/Heimir/pub/ws/Authorization", "Authorization");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://gatewaytest.borgun.is/ws/Heimir.pub.ws:Authorization?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHORIZATION_WSDL_LOCATION = url;
        AUTHORIZATION_EXCEPTION = e;
    }

    public Authorization() {
        super(__getWsdlLocation(), AUTHORIZATION_QNAME);
    }

    public Authorization(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHORIZATION_QNAME, features);
    }

    public Authorization(URL wsdlLocation) {
        super(wsdlLocation, AUTHORIZATION_QNAME);
    }

    public Authorization(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHORIZATION_QNAME, features);
    }

    public Authorization(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Authorization(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthorizationPortType
     */
    @WebEndpoint(name = "Heimir_pub_ws_Authorization_Port")
    public AuthorizationPortType getHeimirPubWsAuthorizationPort() {
        return super.getPort(new QName("http://Borgun/Heimir/pub/ws/Authorization", "Heimir_pub_ws_Authorization_Port"), AuthorizationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorizationPortType
     */
    @WebEndpoint(name = "Heimir_pub_ws_Authorization_Port")
    public AuthorizationPortType getHeimirPubWsAuthorizationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Borgun/Heimir/pub/ws/Authorization", "Heimir_pub_ws_Authorization_Port"), AuthorizationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHORIZATION_EXCEPTION!= null) {
            throw AUTHORIZATION_EXCEPTION;
        }
        return AUTHORIZATION_WSDL_LOCATION;
    }

}
