
package is.valitor.api.fyrirtaekjagreidslur;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import is.valitor.greidslugatt.TegundKorts;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FyrirtaekjagreidslurSoap", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
@XmlSeeAlso({
    is.valitor.api.fyrirtaekjagreidslur.ObjectFactory.class,
    is.valitor.api.fyrirtaekjagreidslur.serverkvittun.ObjectFactory.class,
    is.valitor.greidslugatt.ObjectFactory.class
})
public interface FyrirtaekjagreidslurSoap {


    /**
     * 
     * @param posiID
     * @param lykilord
     * @param samningsnumer
     * @param oryggisnumer
     * @param notandanafn
     * @param samningsKennitala
     * @param gildistimi
     * @param kortnumer
     * @param stillingar
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.SyndarkortnumerSkilabod
     */
    @WebMethod(operationName = "FaSyndarkortnumer", action = "http://api.valitor.is/Fyrirtaekjagreidslur/FaSyndarkortnumer")
    @WebResult(name = "FaSyndarkortnumerResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "FaSyndarkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaSyndarkortnumer")
    @ResponseWrapper(localName = "FaSyndarkortnumerResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaSyndarkortnumerResponse")
    public SyndarkortnumerSkilabod faSyndarkortnumer(
        @WebParam(name = "Notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "Lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "Samningsnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsnumer,
        @WebParam(name = "SamningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "PosiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String posiID,
        @WebParam(name = "Kortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String kortnumer,
        @WebParam(name = "Gildistimi", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String gildistimi,
        @WebParam(name = "Oryggisnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String oryggisnumer,
        @WebParam(name = "Stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param posiID
     * @param lykilord
     * @param samningsnumer
     * @param notandanafn
     * @param samningsKennitala
     * @param gjaldmidill
     * @param stillingar
     * @param syndarkortnumer
     * @param upphaed
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.HeimildSkilabod
     */
    @WebMethod(operationName = "FaHeimild", action = "http://api.valitor.is/Fyrirtaekjagreidslur/FaHeimild")
    @WebResult(name = "FaHeimildResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "FaHeimild", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaHeimild")
    @ResponseWrapper(localName = "FaHeimildResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaHeimildResponse")
    public HeimildSkilabod faHeimild(
        @WebParam(name = "Notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "Lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "Samningsnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsnumer,
        @WebParam(name = "SamningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "PosiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String posiID,
        @WebParam(name = "Syndarkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarkortnumer,
        @WebParam(name = "Upphaed", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String upphaed,
        @WebParam(name = "Gjaldmidill", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String gjaldmidill,
        @WebParam(name = "Stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param posiID
     * @param lykilord
     * @param samningsnumer
     * @param notandanafn
     * @param samningsKennitala
     * @param gjaldmidill
     * @param stillingar
     * @param syndarkortnumer
     * @param upphaed
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.HeimildSkilabod
     */
    @WebMethod(operationName = "FaEndurgreitt", action = "http://api.valitor.is/Fyrirtaekjagreidslur/FaEndurgreitt")
    @WebResult(name = "FaEndurgreittResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "FaEndurgreitt", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaEndurgreitt")
    @ResponseWrapper(localName = "FaEndurgreittResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaEndurgreittResponse")
    public HeimildSkilabod faEndurgreitt(
        @WebParam(name = "Notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "Lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "Samningsnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsnumer,
        @WebParam(name = "SamningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "PosiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String posiID,
        @WebParam(name = "Syndarkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarkortnumer,
        @WebParam(name = "Upphaed", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String upphaed,
        @WebParam(name = "Gjaldmidill", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String gjaldmidill,
        @WebParam(name = "Stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param posiID
     * @param lykilord
     * @param samningsnumer
     * @param notandanafn
     * @param samningsKennitala
     * @param gjaldmidill
     * @param stillingar
     * @param faerslunumer
     * @param syndarkortnumer
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.HeimildSkilabod
     */
    @WebMethod(operationName = "FaOgildingu", action = "http://api.valitor.is/Fyrirtaekjagreidslur/FaOgildingu")
    @WebResult(name = "FaOgildinguResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "FaOgildingu", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaOgildingu")
    @ResponseWrapper(localName = "FaOgildinguResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaOgildinguResponse")
    public HeimildSkilabod faOgildingu(
        @WebParam(name = "Notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "Lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "Samningsnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsnumer,
        @WebParam(name = "SamningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "PosiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String posiID,
        @WebParam(name = "Syndarkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarkortnumer,
        @WebParam(name = "Gjaldmidill", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String gjaldmidill,
        @WebParam(name = "Faerslunumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String faerslunumer,
        @WebParam(name = "Stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param lykilord
     * @param notandanafn
     * @param samningsKennitala
     * @param stillingar
     * @param syndarkortnumer
     * @param nyrGildistimi
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.Skilabod
     */
    @WebMethod(operationName = "UppfaeraGildistima", action = "http://api.valitor.is/Fyrirtaekjagreidslur/UppfaeraGildistima")
    @WebResult(name = "UppfaeraGildistimaResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "UppfaeraGildistima", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.UppfaeraGildistima")
    @ResponseWrapper(localName = "UppfaeraGildistimaResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.UppfaeraGildistimaResponse")
    public Skilabod uppfaeraGildistima(
        @WebParam(name = "Notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "Lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "SamningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "Syndarkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarkortnumer,
        @WebParam(name = "NyrGildistimi", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String nyrGildistimi,
        @WebParam(name = "Stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param lykilord
     * @param notandanafn
     * @param samningsKennitala
     * @param stillingar
     * @param syndarkortnumer
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.KortnumerUtFraSyndarkortnumeriSkilabod
     */
    @WebMethod(operationName = "FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeri", action = "http://api.valitor.is/Fyrirtaekjagreidslur/FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeri")
    @WebResult(name = "FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeriResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeri", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeri")
    @ResponseWrapper(localName = "FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeriResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaSidustuFjoraIKortnumeriUtFraSyndarkortnumeriResponse")
    public KortnumerUtFraSyndarkortnumeriSkilabod faSidustuFjoraIKortnumeriUtFraSyndarkortnumeri(
        @WebParam(name = "Notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "Lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "SamningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "Syndarkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarkortnumer,
        @WebParam(name = "Stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * Netgreiðsla með debetkorti
     * 
     * @param posiID
     * @param lykilord
     * @param samningsnumer
     * @param notandanafn
     * @param samningsKennitala
     * @param tegundKorts
     * @param syndarDebetNumer
     * @param kennitalaKorthafa
     * @param upphaed
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.DebitSvar
     */
    @WebMethod(operationName = "GreidaMedDebetkorti", action = "http://api.valitor.is/Fyrirtaekjagreidslur/GreidaMedDebetkorti")
    @WebResult(name = "GreidaMedDebetkortiResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "GreidaMedDebetkorti", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.GreidaMedDebetkorti")
    @ResponseWrapper(localName = "GreidaMedDebetkortiResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.GreidaMedDebetkortiResponse")
    public DebitSvar greidaMedDebetkorti(
        @WebParam(name = "notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "samningsnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsnumer,
        @WebParam(name = "samningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "posiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        int posiID,
        @WebParam(name = "tegundKorts", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        TegundKorts tegundKorts,
        @WebParam(name = "syndarDebetNumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarDebetNumer,
        @WebParam(name = "kennitalaKorthafa", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String kennitalaKorthafa,
        @WebParam(name = "upphaed", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        double upphaed);

    /**
     * 
     * @param posiID
     * @param lykilord
     * @param samningsnumer
     * @param notandanafn
     * @param samningsKennitala
     * @param gildistimi
     * @param tekkaabyrgdarnumer
     * @param tegundKorts
     * @param kennitalaKorthafa
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.SyndarkortnumerSkilabod
     */
    @WebMethod(operationName = "FaSyndarDebetkortnumer", action = "http://api.valitor.is/Fyrirtaekjagreidslur/FaSyndarDebetkortnumer")
    @WebResult(name = "FaSyndarDebetkortnumerResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "FaSyndarDebetkortnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaSyndarDebetkortnumer")
    @ResponseWrapper(localName = "FaSyndarDebetkortnumerResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.FaSyndarDebetkortnumerResponse")
    public SyndarkortnumerSkilabod faSyndarDebetkortnumer(
        @WebParam(name = "notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "samningsnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsnumer,
        @WebParam(name = "samningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "posiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String posiID,
        @WebParam(name = "tegundKorts", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        TegundKorts tegundKorts,
        @WebParam(name = "kennitalaKorthafa", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String kennitalaKorthafa,
        @WebParam(name = "tekkaabyrgdarnumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String tekkaabyrgdarnumer,
        @WebParam(name = "gildistimi", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String gildistimi);

    /**
     * 
     * @param lykilord
     * @param notandanafn
     * @param samningsKennitala
     * @param stillingar
     * @param syndarDebetNumer
     * @param nyrGildistimi
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.Skilabod
     */
    @WebMethod(operationName = "UppfaeraDebetkortaGildistima", action = "http://api.valitor.is/Fyrirtaekjagreidslur/UppfaeraDebetkortaGildistima")
    @WebResult(name = "UppfaeraDebetkortaGildistimaResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "UppfaeraDebetkortaGildistima", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.UppfaeraDebetkortaGildistima")
    @ResponseWrapper(localName = "UppfaeraDebetkortaGildistimaResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.UppfaeraDebetkortaGildistimaResponse")
    public Skilabod uppfaeraDebetkortaGildistima(
        @WebParam(name = "notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "samningsKennitala", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String samningsKennitala,
        @WebParam(name = "syndarDebetNumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String syndarDebetNumer,
        @WebParam(name = "nyrGildistimi", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String nyrGildistimi,
        @WebParam(name = "stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param posiID
     * @param lykilord
     * @param notandanafn
     * @param stillingar
     * @param sidustuFjorirITekkaabyrgdarnumeri
     * @param faerslunumer
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.HeimildSkilabod
     */
    @WebMethod(operationName = "OgildaDebetFaerslu", action = "http://api.valitor.is/Fyrirtaekjagreidslur/OgildaDebetFaerslu")
    @WebResult(name = "OgildaDebetFaersluResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "OgildaDebetFaerslu", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.OgildaDebetFaerslu")
    @ResponseWrapper(localName = "OgildaDebetFaersluResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.OgildaDebetFaersluResponse")
    public HeimildSkilabod ogildaDebetFaerslu(
        @WebParam(name = "notandanafn", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String notandanafn,
        @WebParam(name = "lykilord", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String lykilord,
        @WebParam(name = "posiID", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String posiID,
        @WebParam(name = "sidustuFjorirITekkaabyrgdarnumeri", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String sidustuFjorirITekkaabyrgdarnumeri,
        @WebParam(name = "faerslunumer", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String faerslunumer,
        @WebParam(name = "stillingar", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        String stillingar);

    /**
     * 
     * @param request
     * @return
     *     returns is.valitor.api.fyrirtaekjagreidslur.PaymentResponse
     */
    @WebMethod(operationName = "CreatePayment", action = "http://api.valitor.is/Fyrirtaekjagreidslur/CreatePayment")
    @WebResult(name = "CreatePaymentResult", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
    @RequestWrapper(localName = "CreatePayment", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.CreatePayment")
    @ResponseWrapper(localName = "CreatePaymentResponse", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/", className = "is.valitor.api.fyrirtaekjagreidslur.CreatePaymentResponse")
    public PaymentResponse createPayment(
        @WebParam(name = "request", targetNamespace = "http://api.valitor.is/Fyrirtaekjagreidslur/")
        PaymentRequest request);

}
